// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: email.proto

package emailclient

import (
	"context"

	"github.com/boyyang-love/micro-service-wallpaper-rpc/email/pb/email"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Base             = email.Base
	SendEmailCodeReq = email.SendEmailCodeReq
	SendEmailCodeRes = email.SendEmailCodeRes
	SendEmailReq     = email.SendEmailReq
	SendEmailRes     = email.SendEmailRes

	Email interface {
		SendEmail(ctx context.Context, in *SendEmailReq, opts ...grpc.CallOption) (*SendEmailRes, error)
		SendEmailCode(ctx context.Context, in *SendEmailCodeReq, opts ...grpc.CallOption) (*SendEmailCodeRes, error)
	}

	defaultEmail struct {
		cli zrpc.Client
	}
)

func NewEmail(cli zrpc.Client) Email {
	return &defaultEmail{
		cli: cli,
	}
}

func (m *defaultEmail) SendEmail(ctx context.Context, in *SendEmailReq, opts ...grpc.CallOption) (*SendEmailRes, error) {
	client := email.NewEmailClient(m.cli.Conn())
	return client.SendEmail(ctx, in, opts...)
}

func (m *defaultEmail) SendEmailCode(ctx context.Context, in *SendEmailCodeReq, opts ...grpc.CallOption) (*SendEmailCodeRes, error) {
	client := email.NewEmailClient(m.cli.Conn())
	return client.SendEmailCode(ctx, in, opts...)
}
