// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: upload.proto

package server

import (
	"context"

	"github.com/boyyang-love/micro-service-wallpaper-rpc/upload/internal/logic"
	"github.com/boyyang-love/micro-service-wallpaper-rpc/upload/internal/svc"
	"github.com/boyyang-love/micro-service-wallpaper-rpc/upload/pb/upload"
)

type UploadServer struct {
	svcCtx *svc.ServiceContext
	upload.UnimplementedUploadServer
}

func NewUploadServer(svcCtx *svc.ServiceContext) *UploadServer {
	return &UploadServer{
		svcCtx: svcCtx,
	}
}

func (s *UploadServer) FileUpload(ctx context.Context, in *upload.FileUploadReq) (*upload.FileUploadRes, error) {
	l := logic.NewFileUploadLogic(ctx, s.svcCtx)
	return l.FileUpload(in)
}

func (s *UploadServer) ImageUpload(ctx context.Context, in *upload.ImageUploadReq) (*upload.ImageUploadRes, error) {
	l := logic.NewImageUploadLogic(ctx, s.svcCtx)
	return l.ImageUpload(in)
}

func (s *UploadServer) ImageDelete(ctx context.Context, in *upload.ImageDeleteReq) (*upload.Base, error) {
	l := logic.NewImageDeleteLogic(ctx, s.svcCtx)
	return l.ImageDelete(in)
}

func (s *UploadServer) CosUpload(ctx context.Context, in *upload.ImageUploadReq) (*upload.ImageUploadRes, error) {
	l := logic.NewCosUploadLogic(ctx, s.svcCtx)
	return l.CosUpload(in)
}

func (s *UploadServer) CosDelete(ctx context.Context, in *upload.ImageDeleteReq) (*upload.Base, error) {
	l := logic.NewCosDeleteLogic(ctx, s.svcCtx)
	return l.CosDelete(in)
}
